// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: func.proto

package img

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Func is a function definition provided by the Package.
type Func struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Function name (package level only).
	//
	// Used to lookup function during bootstrap.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Data segment size in bytes.
	DataSize uint32 `protobuf:"varint,2,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	// Arguments size in bytes.
	//
	// Arguments are part of the data segment.
	ArgsSize uint32 `protobuf:"varint,3,opt,name=args_size,json=argsSize,proto3" json:"args_size,omitempty"`
	// Immediate data segment.
	//
	// Immediate segment is an immutable
	// data block with compile time constants.
	Immediate []byte `protobuf:"bytes,4,opt,name=immediate,proto3" json:"immediate,omitempty"`
	// Source code segment.
	Source        []byte   `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	CallInfo      []uint32 `protobuf:"varint,6,rep,packed,name=call_info,json=callInfo,proto3" json:"call_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Func) Reset() {
	*x = Func{}
	mi := &file_func_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Func) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Func) ProtoMessage() {}

func (x *Func) ProtoReflect() protoreflect.Message {
	mi := &file_func_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Func.ProtoReflect.Descriptor instead.
func (*Func) Descriptor() ([]byte, []int) {
	return file_func_proto_rawDescGZIP(), []int{0}
}

func (x *Func) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Func) GetDataSize() uint32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *Func) GetArgsSize() uint32 {
	if x != nil {
		return x.ArgsSize
	}
	return 0
}

func (x *Func) GetImmediate() []byte {
	if x != nil {
		return x.Immediate
	}
	return nil
}

func (x *Func) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Func) GetCallInfo() []uint32 {
	if x != nil {
		return x.CallInfo
	}
	return nil
}

var File_func_proto protoreflect.FileDescriptor

const file_func_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"func.proto\x12\x03img\"\xa7\x01\n" +
	"\x04Func\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_size\x18\x02 \x01(\rR\bdataSize\x12\x1b\n" +
	"\targs_size\x18\x03 \x01(\rR\bargsSize\x12\x1c\n" +
	"\timmediate\x18\x04 \x01(\fR\timmediate\x12\x16\n" +
	"\x06source\x18\x05 \x01(\fR\x06source\x12\x1b\n" +
	"\tcall_info\x18\x06 \x03(\rR\bcallInfoB\aZ\x05./imgb\x06proto3"

var (
	file_func_proto_rawDescOnce sync.Once
	file_func_proto_rawDescData []byte
)

func file_func_proto_rawDescGZIP() []byte {
	file_func_proto_rawDescOnce.Do(func() {
		file_func_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_func_proto_rawDesc), len(file_func_proto_rawDesc)))
	})
	return file_func_proto_rawDescData
}

var file_func_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_func_proto_goTypes = []any{
	(*Func)(nil), // 0: img.Func
}
var file_func_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_func_proto_init() }
func file_func_proto_init() {
	if File_func_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_func_proto_rawDesc), len(file_func_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_func_proto_goTypes,
		DependencyIndexes: file_func_proto_depIdxs,
		MessageInfos:      file_func_proto_msgTypes,
	}.Build()
	File_func_proto = out.File
	file_func_proto_goTypes = nil
	file_func_proto_depIdxs = nil
}
