syntax = "proto3";

package img;

option go_package = "./img";

// Func is a function definition provided by the Package.
message Func {
  // Function name (package level only).
  //
  // Used to lookup function during bootstrap.
  string name = 1;

  // Data segment size in bytes.
  uint32 data_size = 2;

  // Arguments size in bytes.
  //
  // Arguments are part of the data segment.
  uint32 args_size = 3;

  // Immediate data segment.
  //
  // Immediate segment is an immutable
  // data block with compile time constants.
  bytes immediate = 4;

  // Source code segment.
  bytes source = 5;

  repeated uint32 call_info = 6;
}
