// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg.proto

package img

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Package is a topmost logical unit of a progam.
//
// Package contains list of function definitions
// and immutable data segment.
type Package struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package name.
	//
	// Used to lookup package during bootstrap.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Package immediate data segment.
	//
	// Immediate segment is an immutable
	// data block with compile time constants.
	Immediate []byte `protobuf:"bytes,2,opt,name=immediate,proto3" json:"immediate,omitempty"`
	// Provided function definitions.
	//
	// Functions called by their local number,
	// so the order in which they appears here
	// must be persisted.
	Funcs         []*Func `protobuf:"bytes,3,rep,name=funcs,proto3" json:"funcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_pkg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetImmediate() []byte {
	if x != nil {
		return x.Immediate
	}
	return nil
}

func (x *Package) GetFuncs() []*Func {
	if x != nil {
		return x.Funcs
	}
	return nil
}

var File_pkg_proto protoreflect.FileDescriptor

const file_pkg_proto_rawDesc = "" +
	"\n" +
	"\tpkg.proto\x12\x03img\x1a\n" +
	"func.proto\"\\\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\timmediate\x18\x02 \x01(\fR\timmediate\x12\x1f\n" +
	"\x05funcs\x18\x03 \x03(\v2\t.img.FuncR\x05funcsB\aZ\x05./imgb\x06proto3"

var (
	file_pkg_proto_rawDescOnce sync.Once
	file_pkg_proto_rawDescData []byte
)

func file_pkg_proto_rawDescGZIP() []byte {
	file_pkg_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rawDesc), len(file_pkg_proto_rawDesc)))
	})
	return file_pkg_proto_rawDescData
}

var file_pkg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_goTypes = []any{
	(*Package)(nil), // 0: img.Package
	(*Func)(nil),    // 1: img.Func
}
var file_pkg_proto_depIdxs = []int32{
	1, // 0: img.Package.funcs:type_name -> img.Func
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_init() }
func file_pkg_proto_init() {
	if File_pkg_proto != nil {
		return
	}
	file_func_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rawDesc), len(file_pkg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_goTypes,
		DependencyIndexes: file_pkg_proto_depIdxs,
		MessageInfos:      file_pkg_proto_msgTypes,
	}.Build()
	File_pkg_proto = out.File
	file_pkg_proto_goTypes = nil
	file_pkg_proto_depIdxs = nil
}
