syntax = "proto3";

package img;

import "func.proto";

option go_package = "./img";

// Package is a topmost logical unit of a progam.
//
// Package contains list of function definitions
// and immutable data segment.
message Package {
  // Package name.
  //
  // Used to lookup package during bootstrap.
  string name = 1;

  // Package immediate data segment.
  //
  // Immediate segment is an immutable
  // data block with compile time constants.
  bytes immediate = 2;

  // Provided function definitions.
  //
  // Functions called by their local number,
  // so the order in which they appears here
  // must be persisted.
  repeated Func funcs = 3;
}
